# Generated by Django 5.1.4 on 2024-12-10 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="payment_date",
            new_name="date",
        ),
        migrations.AddField(
            model_name="loan",
            name="amount_repaid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="payment",
            name="loan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="repayments",
                to="loans.loan",
            ),
        ),
    ]
